refactor(PaperService, NotifyService): Simplify the code
nju-softeng/dingtalk-app-server pull request #78
Opened 2021-12-05 11:50 UTC by lilingj

用了一些stream的特性，简化了一下代码。

2021-12-05 12:03 UTC, zhanyeye commented
收到~，最近有些忙，我争取快点看完合入哈~

2021-12-06 12:01 UTC, zhanyeye commented on src/main/java/com/softeng/dingtalk/service/BugService.java
> +        if (!vo.isStatus()) {
Why Use !boolean_variable Over boolean_variable == false：
https://softwareengineering.stackexchange.com/a/136914

2021-12-06 12:05 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/BugService.java
> +        if (!vo.isStatus()) {
一是个人习惯，二是idea报可以简化的提示，三是好像在哪看到，bool值不应该用==和!=去判断

2021-12-06 12:06 UTC, zhanyeye commented on src/main/java/com/softeng/dingtalk/service/BugService.java
> +        if (!vo.isStatus()) {
我们的这个变量名没有体现出它的意思，不过bugService开发出来也没人用😂

2021-12-06 12:08 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/BugService.java
> +        if (!vo.isStatus()) {
这确实是个问题，status和result，有时候我看着看着代码就晕了

2021-12-06 12:11 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/BugService.java
> +        if (!vo.isStatus()) {
重构的时候考虑用enum把这些状态值都替换了

2021-12-07 02:23 UTC, zhanyeye requested changes
非常优秀了，学到好多东西，只是有一些事务失效的bug需要解决

2021-12-07 02:23 UTC, zhanyeye commented on src/main/java/com/softeng/dingtalk/service/SystemService.java
> +                .flatMap(depId -> contactsApi.listUserId(depId).stream())
”stream api 的 flatMap方法接受一个lambda表达式函数， 函数的返回值必须也是一个stream类型，flatMap方法最终会把所有返回的stream合并“，学习到啦

2021-12-07 02:28 UTC, zhanyeye commented
学弟把问题解决后，可以点击 `resolve conversation` 哈

2021-12-07 02:52 UTC, zhanyeye commented
学弟这一次提交的代码量好多😂
+ MR的最佳实践是少量多次，这样review 的速度会快一点，如果是大的 feature 改动，可以分成多个小MR 分次提交~
+ 学弟也可以将分支命名为 `personal/lilingj/xxxxxx_task_name`
+ 如果是一个大特性改动，也可以从 `main` 创建一个 `feature/xxxxxx` 然后 mr 到 `feature/xxxxxx` 上

2021-12-07 02:58 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/AuditService.java
> +import javax.swing.text.html.Option;
可能是输错了，idea自动补全了没删

2021-12-07 03:07 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/PaperService.java
> -        paperDetails.forEach(pd -> performanceService.computeSalary(pd.getUser().getId(), LocalDate.now()));
我的想法是统一更新dc_summary。如果dc_summary依赖的表更新它就更新的话，要考虑的东西好像有点多，而且如果某个依赖表频繁更新，就会触发dc_summary频繁更新，性能也不太好。

2021-12-07 03:09 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/PerformanceService.java
> -        computeSalary(uid, yearmonth);
给系统管理员一个刷新按钮，定时刷新 + 手动刷新怎么样？

2021-12-07 03:10 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/PerformanceService.java
> +        DcSummary dc = Optional.ofNullable(dcSummaryRepository.findByUserIdAndYearmonth(uid, yearmonth))
跟学长代码学的，这里面不写Optional，我还不知道有这个用法。

2021-12-07 03:17 UTC, zhanyeye commented on src/main/java/com/softeng/dingtalk/service/PerformanceService.java
> -        computeSalary(uid, yearmonth);
topup 是用户的额外补贴，修改后总助研金应该是立即更新的，

2021-12-07 03:21 UTC, zhanyeye commented on src/main/java/com/softeng/dingtalk/service/PaperService.java
> -        paperDetails.forEach(pd -> performanceService.computeSalary(pd.getUser().getId(), LocalDate.now()));
这个确实是要考虑，现在的代码会导致数据不准确，可能会被用户吐槽的。
此外还有一个问题，computeSalary 会累积求和所有的历史AC, 如果AC_Record数据量大的话，性能一定会有问题，面试时就被问过，这是个难点。

2021-12-07 03:28 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/PaperService.java
> -        paperDetails.forEach(pd -> performanceService.computeSalary(pd.getUser().getId(), LocalDate.now()));
绩效刷新这块问题我明白了，我再考虑考虑

2021-12-07 03:29 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/PaperService.java
> +            calculateInternalPaperAc(internalPaper);
我先去看看SpringBoot事务是怎么工作的

2021-12-07 09:42 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/NotifyService.java
> +        autoSetProjectAcMessage(acRecords);
动态代理实现下调用自身函数导致事务失效的情形我大概明白了，比如A.a调用A.b，A.b抛出异常，那么A.b不会回滚，因为从内部调用的方法没有被SpringBoot动态代理。但是我们的实现设想的情景并不是这样，我们隐含的假设是A.b只是个内联函数，虽然A.b不会回滚，但是如果A.b抛出异常，A.a会回滚，整体的事务仍然没有失效。
        我自己测了一下，类似A.a调A.b，A.b负责插入数据，然后抛出异常，数据库并没有写入，说明A.a本身是回滚了。

2021-12-07 13:29 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/PaperService.java
> +        externalPaperRepository.save(externalPaper);
确实是个bug，要用数据库去获取自增id

2021-12-08 06:17 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/component/Timer.java
> +            );
主要是想突出函数的功能，将主要动作放在开头。在IDE中有参数提示读起来比较容易

2021-12-08 06:19 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/PaperService.java
> +        externalPaperRepository.save(externalPaper);
已修改

2021-12-08 06:21 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/PaperService.java
> -        paperDetails.forEach(pd -> performanceService.computeSalary(pd.getUser().getId(), LocalDate.now()));
我想这块放到以后再考虑。可以定时压缩，建个新表，专门存放历史ac_record，原表每个月压缩一次

2021-12-08 06:24 UTC, lilingj commented on src/main/java/com/softeng/dingtalk/service/PerformanceService.java
> -        computeSalary(uid, yearmonth);
已改回

2021-12-08 15:20 UTC, lilingj commented
事务失效部分已修改

2021-12-08 15:23 UTC, zhanyeye approved these changes

2021-12-08 15:23 UTC, merged